name: Check branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: Install pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          runtime: node@24
          version: 11
          cache: false
      - name: Run Tests
        run: 'pnpm run test:ci'
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: Install pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          runtime: node@24
          version: 11
          cache: false
      - name: Check Types
        run: 'pnpm run typecheck'
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: Install pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          runtime: node@24
          version: 11
          cache: false
      - name: Check Formatting
        run: 'pnpm run format:check'
