name: Deploy Documentation to Cloudflare Pages on merge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: Install pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          runtime: node@24
          version: 11
          cache: false
      - name: Build
        run: 'pnpm run docs:build'
      - name: Publish
        uses: cloudflare/pages-action@df669237a4d8f43d1725c6377f25fd69c08ab1f1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'sqlocal-docs'
          directory: 'docs/.vitepress/dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
